// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFsXkMVTlSQfJCl7HlnL7PnKyPbME9Zk',
    appId: '1:841177859782:web:e6928cc68a44f1e29db9c7',
    messagingSenderId: '841177859782',
    projectId: 'idea-cbca1',
    authDomain: 'idea-cbca1.firebaseapp.com',
    storageBucket: 'idea-cbca1.firebasestorage.app',
    measurementId: 'G-KP6V3GNDRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMlCxHKW99_WDzs2SGwd_bolM7dCqfqI',
    appId: '1:841177859782:android:3f42f6ddd5000eea9db9c7',
    messagingSenderId: '841177859782',
    projectId: 'idea-cbca1',
    storageBucket: 'idea-cbca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fhIogEDFB2LIJSF1y1eq3Z-SoKR8DHs',
    appId: '1:841177859782:ios:7cb315947398dfb09db9c7',
    messagingSenderId: '841177859782',
    projectId: 'idea-cbca1',
    storageBucket: 'idea-cbca1.firebasestorage.app',
    iosBundleId: 'com.example.idea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fhIogEDFB2LIJSF1y1eq3Z-SoKR8DHs',
    appId: '1:841177859782:ios:7cb315947398dfb09db9c7',
    messagingSenderId: '841177859782',
    projectId: 'idea-cbca1',
    storageBucket: 'idea-cbca1.firebasestorage.app',
    iosBundleId: 'com.example.idea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTFsXkMVTlSQfJCl7HlnL7PnKyPbME9Zk',
    appId: '1:841177859782:web:cb388cf24ad290be9db9c7',
    messagingSenderId: '841177859782',
    projectId: 'idea-cbca1',
    authDomain: 'idea-cbca1.firebaseapp.com',
    storageBucket: 'idea-cbca1.firebasestorage.app',
    measurementId: 'G-1VLS6MX2X3',
  );
}
